name = "abstract-algebra"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["AbstractAlgebra"]

[leanOptions]
pp.unicode.fun = true # Pretty-print lambdas as `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.16.0"

[[lean_lib]]
name = "AbstractAlgebra"
